### ISSUE TITLE
1.2.0 linux release package references 1.1.1 versioning

### ISSUE THREAD

**Issue by kasper-piskorski** [graknlabs/workbase#109]
## Description
The 1.2.0 release distribution references 1.1.1 still:

![image](https://user-images.githubusercontent.com/10519067/55321562-e4e8a400-5471-11e9-8ef7-344b7f32ebd0.png)

**Comment by vmax** [comment]
Reason for this is not updating the version in [this line](https://github.com/graknlabs/workbase/blob/master/package.json#L163)
