### ISSUE TITLE
Explanation of a concept whose explanation answer contains an inferred relationship fails

### ISSUE THREAD

**Issue by Irtazaraza** [graknlabs/workbase#131]
## Description

Since the transaction that attached the explanation object to a concept was closed.
When the user explains a concept that has an inferred relationship with its "un-persisted" id part of the query pattern. It fails.

## Environment

2. Grakn version (and platform): Grakn Core 1.5
3. Workbase version (and OS): Workbase 1.2 on Mac

## Reproducible Steps
```
define

person sub entity,
	plays child,
	plays parent;

fatherhood sub relation,
	relates child,
	relates parent;

parentship sub relation,
	relates child,
	relates parent;

rule1 sub rule,
when {
	(child: $x, parent: $y) isa fatherhood;
}, then {
	(child: $x, parent: $y) isa parentship;
};

insert $x isa person; $y isa person; $r (child: $x, parent: $y) isa fatherhood;
```
1) load above schema and data
2) explain parentship

## Expected Output
explanation

## Actual Output
no response

## Additional Information
relient on issue https://github.com/graknlabs/grakn/issues/5268

**Comment by vughtwv** [comment]
I also have this issue on windows, however, it looks like sometimes workbase does show explanations and sometimes not for the exact same concept (a restart of workbase often helps for me...). Hope the problem is fixed soon :)

**Comment by sorsaffari** [comment]
## Alternate explanation of the issue
At the moment, explaining a relation that is inferred via other inferred concepts is not possible because the id of the underlying inferred concept is generated at query time and is bound to exist only within the transaction that executed the original query. Because of this, we are currently unable to explain such inferred concepts via Workbase.

## As an experiment, we will:
Use one single transaction for executing the original query and any subsequent queries or calling the Concept API methods, as long as:
- the graph has not been cleared,
- the keyspace has not been changed, or
- the interface has not been changed.

**Comment by sorsaffari** [comment]
@marco-scoppetta 

From what I've seen the transaction object is mutated when calling its functions (not only `query()` but also the concept API methods). That's a conclusion I'm making by observing that upon calling functions on `transaction`, `Vuex` complains that:

```
Error: [vuex] do not mutate Vuex store state outside mutation handlers.
```

This behaviour is consistent whether we get the `graknTransaction` off of `state` available in the `context` passed to the Vuex `action`, or when we use the `getter` to obtain it.

I don't have enough context to know how we (or gRPC?) mutates the transaction object and if it is at all possible to make it immutable.

I'm now thinking of an alternative to `state` for storing the `transaction` object. `localStorage` perhaps? but again if the `transaction` is mutated one every call, would that mean, wherever we store it, it needs to be updated after every (or a series of) calls made on it? I don't know the answer, and so will continue experimenting.

Please let me know if you have any ideas

**Comment by sorsaffari** [comment]
@marco-scoppetta 
could [this](https://github.com/graknlabs/client-nodejs/blob/bb010104c41ff802de464ca333107ad51b404f0b/src/service/Session/util/GrpcCommunicator.js#L45) be where we mutate the transaction object?

**Comment by sorsaffari** [comment]
@marco-scoppetta Here is how it went with the global `transaction` approach

Strangely, using a variable at the global scope of `Visualiser > store >actions.js` leads to the same Vuex error but at a later stage!

Here are the steps I took:
1. `graknTransaction` is declared just before the `export default`
2. `graknTransaction` is initialised in the `CURRENT_KEYSPACE_CHANGED` action
3. `graknTransaction` is used in place of `graknTx` while removing all former instantiations of `graknTx`
4. `graknTransaction` is never closed

Here is the outcome:
1. `RUN_CURRENT_QUERY` completes with no errors
2. `EXPLAIN_CONCEPT` throws the same Vuex error (oy! don't mutate outside mutation handlers) on line `const result = (await (await graknTransaction.query(query)).collect());` and any subsequent lines where a method is called on `graknTransaction` or on any of the concepts that are bound to the same transaction.

**Comment by mingfang** [comment]
I'm still seeing this problem.
What was the fix?

**Comment by sorsaffari** [comment]
@mingfang 
could the issue you're facing be related to what's explained in the "Important" note here on [this page](http://dev.grakn.ai/docs/workbase/overview)?

**Comment by mingfang** [comment]
@sorsaffari Thanks for the reply.  The problem was caused by my own changes.  I'm in the middle of converting Workbase from an Electron app into a pure web app using websockets.  I had an async function updating the Vue state that was causing this error, which is now fixed. Thanks again.

**Comment by sorsaffari** [comment]
you're welcome @mingfang. Glad you sorted it out :)
