### ISSUE TITLE
Rule Definer: Error on new rule

### ISSUE THREAD

**Issue by Kingloko** [graknlabs/workbase#142]
## Description

Adding a rule from workbase causes an error, while adding the exact same rule via the console is fine. 

## Environment

1. Grakn version: Grakn Core 1.5.2
2. OS of Grakn server: Ubuntu 16.4
3. Workbase version: 1.2.1
4. OS of Workbase: Ubuntu 18.04
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
It seems I cant upload screen shots, but one is available in slack. 
The following is the text I supplied to the form:
name: gp_rule2
when: 
```
(parent: $a, child: $b) isa parentOf;
(parent: $b, child: $c) isa parentOf;
```
then:
```
(gprnt: $a, gc: $c) isa grandparentOf;
```
## Expected Output

rule added without a problem

## Actual Output

```
no viable alternative at input '{(parent: $a, child: $b) isa parentOf;\n(parent: $b, child: $c) isa parentOf;\n}'
syntax error at line 3:
}
 ^
```
 
## Additional information

I tried creating this exact same rule via the console and had no problem:
```
define
------

person sub entity,
    plays gc,
    plays gprnt,
    plays child,
    plays parent;

parentOf sub relation,
    relates child,
    relates parent;

grandparentOf sub relation,
    relates gprnt,
    relates gc;

gp sub rule,
when{
(parent: $a, child: $b) isa parentOf;
(parent: $b, child: $c) isa parentOf;
}, then {
(gprnt: $a, gc: $c) isa grandparentOf;
};
````

**Comment by Irtazaraza** [comment]
Is a nodejs-client bug: refer to https://github.com/graknlabs/client-nodejs/issues/42

**Comment by sorsaffari** [comment]
@Irtazaraza we need to follow up with the issue you have referred the author to.
