### ISSUE TITLE
error on 'mean' query

### ISSUE THREAD

**Issue by tsl-karlp** [graknlabs/workbase#143]
## Description

![image](https://user-images.githubusercontent.com/40211317/57881421-3fa24900-77ef-11e9-9fc0-0b19c0a2e3f5.png)

The query:

```
match   
  $customer isa person, has age > 40;
  $company isa company, has name "Telecom";
  (customer: $customer, provider: $company) isa contract;
  (caller: $customer, callee: $anyone) isa call, has duration $duration; 
get $duration; mean $duration; 
```
Results in the error:
```
syntax error at line 1: 
match $customer isa person, has age > 40; $company isa company, has name "Telecom"; (customer: $customer, provider: $company) isa contract; (caller: $customer, callee: $anyone) isa call, has duration $duration; get $duration; mean $duration; offset 0; limit 30;
^
mismatched input 'offset' expecting {'match', 'define', 'undefine', 'insert', 'compute'}. Please check server logs for the stack trace.
```

I think it's because `offset 0; limit 30;` is added to the query, when it shouldn't be.

## Environment
1. Grakn version:1.5.3, 
2. OS of Grakn server: Docker version 18.09.2, build 6247962
3. Grakn Workspace Version 1.2.1 (1.2.1.1471)
4. OS of Workbase: Mac OS 10.14.4 (18E226)
5. Other environment details:

**Comment by Irtazaraza** [comment]
Hi @tsl-karlp,

Thank you for submitting this issue. Currently Workbase does not support queries other than match get and compute path. 

We will have these queries running on workbase in the near future. 

Kind regards,
Syed

**Comment by sorsaffari** [comment]
we should handle this error differently and show an appropriate error message.

**Comment by sorsaffari** [comment]
will be tracked and resolved via https://github.com/graknlabs/workbase/issues/171
