### ISSUE TITLE
Bazelise Workbase where nodejs is properly integrated

### ISSUE THREAD

**Issue by lolski** [graknlabs/workbase#17]
* End goal is to be able to run:

`bazel build //:distribution`
`bazel test //:tests-unit`
`bazel test //:tests-e2e`

on all three platforms: Mac/Linux/Windows

#  Difficulties encountered so far [to be updated]
- native grpc binaries have two flavours (`electron` and `node`) — only unit tests require `node` flavour. while re-installing them every time is feasible when doing `npm`-only workflow, it's not the same with `bazel` -- dependencies are designed to be installed during loading phase
- sandbox imposes certain limits:
-- `node_modules/.bin` is not being copied to sandbox which means we'll need to invoke needed binaries (i.e `electron-builder`)
-- had errors on CircleCI's linux machine related to `detect-libc`

**Comment by vmax** [comment]
We decided to not go the `bazel` route for now. I'll outline the new scheme for CI integration in a new issue.
