### ISSUE TITLE
Inferred attributes are drawn multiple times because they have different IDs

### ISSUE THREAD

**Issue by marco-scoppetta** [graknlabs/workbase#188]
## Description

When querying for inferred concepts when get back nodes with randomly generated IDs.

In the case of inferred attributes we might receive 2 nodes that have the same value but different IDs, we should probably just show the attribute once.

## Reproducible Steps

Create a schema with a rule which infers an attribute and trying querying for it (probably need to fetch the same attribute using multiple queries so that the IDs of the inferred attribute will actually be different).

## Expected Output

1 attribute node with a given value

## Actual Output

2 nodes with the same type and value:

![image](https://user-images.githubusercontent.com/6430514/63331565-dbcb7700-c32d-11e9-9833-28c7b382f9cc.png)

**Comment by sorsaffari** [comment]
closing because inferred attributes of the same type and value no longer hold different `id`s
