### ISSUE TITLE
Auto-Loading roleplayers shows all roles of role hierarchy

### ISSUE THREAD

**Issue by jmsfltchr** [graknlabs/workbase#236]
## Description

When running a query for a relation, with `Load Roleplayers` `On`, for each roleplayer of each relation an edge will be drawn for all of the roles it logically plays. Contrary to the normal display of roles, this doesn't just draw the most specific role, but also all of the super roles in the hierarchy.

## Environment

1. Grakn version: Grakn Core 1.5.9
2. OS of Grakn server: Mac OS 10
3. Workbase version: 1.2.5 snapshot
4. OS of Workbase: Mac OS 10

## Reproducible Steps

Steps to create the smallest reproducible scenario:

Use a schema which has a relation with role inheritance
```
define
association sub relation,
    relates associated;

gene-disease-association sub association,
    relates associated-disease as associated,
    relates associated-gene as associated;
```

Insert a `gene-disease-association` with roleplayers, and query for just the relation, with `Load Roleplayers` `On`

## Expected Output

We expect single edges to the roleplayers, either of type `associated-disease` or `associated-gene`

## Actual Output

We have the role edges described, plus an additional edge for the role `associated` for each roleplayer - see image.
 
![Screenshot 2019-10-11 at 16 46 32](https://user-images.githubusercontent.com/38212943/66666392-6bafe200-ec48-11e9-90c2-43bc76120db8.png)

**Comment by sorsaffari** [comment]
resolved via #238
