### ISSUE TITLE
Workbase Drops Text From Queries in Text Editor

### ISSUE THREAD

**Issue by mmscibor** [graknlabs/workbase#249]
## Description

Under certain circumstances, when submitting a query via Workbase, parts of the query's text will be dropped and the query will then fail to run due to a syntax error.

## Environment

1. Grakn version: Grakn Core 1.6.0
2. OS of Grakn server: GCP `n1-standard-32`; `debian-9-stretch-v20191014` 
3. Workbase version: 1.2.2
4. OS of Workbase: Mac OS 10.14.6
5. Other environment details: N/A

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Create a query that spans multiple lines.
2. Try to run that query and observe whether any of the text is truncated from the query.
3. If no text is truncated, try first submitting a query with a syntax error, then re-running steps (1) and (2)

## Expected Output

Query executes and outputs either the result or a message box indicating error.

## Actual Output

Parts of the query are truncated from the text box, then the query is run (due to truncation, almost certainly with errors).
 
## Additional information

![Sample](https://user-images.githubusercontent.com/4494240/70460430-4a227980-1a84-11ea-9b13-d65f5cfaa812.gif)

**Comment by BFergerson** [comment]
I'm able to re-create this issue when I follow the note about inferred transitive relations here: https://github.com/graknlabs/docs/blob/master/07-workbase/00-overview.md#download-workbase

When I don't label the relations ($r1, $r2), then this issue does not occur.
