### ISSUE TITLE
Workbase explain return very partial answer (with no relations)

### ISSUE THREAD

**Issue by maydanw** [graknlabs/workbase#252]
## Description

Pressing Explain returns only part of the entities and none of the relations.

## Environment

1. Grakn version: 1.6.1 
2. OS of Grakn server: Windows 10
3. Workbase version:  1.2.7
4. OS of Workbase: Windows 10

## Reproducible Steps
Steps to create the smallest reproducible scenario:
I saw it even in a very simple scenario:
1. Create 3 entities of different types in a schema where A is associated with B and B is associated with C (A->B->C).
2. Create a rule when A->B and B->C then A->C
3. Insert a few instances of the data to match the schema
3. Create a query in the Workbase to get all the A entities associated with C (this association was added through the rule).
 
## Expected Output
An entity of type B with it's relations to A and B

## Actual Output
An entity of type B will be shown with no relations
 
## Additional information
On a more complex case where the associations are more complex (C->D->E and the rule is creating A->E relation), still, only a single entity (with no relations) is retrieved.

**Comment by sorsaffari** [comment]
@maydanw do the reproducible steps miss the step of explaining the relation between A and C? only then we could expect to see the association between A and B as well as between B and C, as the explanation, right?

**Comment by sorsaffari** [comment]
as of Workbase 1.3.0, users are notified of when and why visualised explanations are partial. the proper fix will be included in `grakn-core`
