### ISSUE TITLE
Insert queries in Workbase update the GUI but not the server

### ISSUE THREAD

**Issue by maydanw** [graknlabs/workbase#254]
## Description
Insert queries in Workbase update the GUI but not the server

## Environment

1. Grakn version: 1.6.1
2. OS of Grakn server: Windows 10
3. Workbase version: 1.2.7
4. OS of Workbase: Windows 10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Add an attribute to an entity (or a relation) through the Workbase
2. See it added to the graph
3. Open a new tab and query the entity and the newly added attribute

## Expected Output
Either a notification "insert is not supported" or an update of the backend.
Even change the background color and add a clear text notifying this is a theoretical graph in which updates are only made for representation purposes and are not saved.    

## Actual Output
The GUI is being updated while the backend isn't which is confusing for newcomers.

**Comment by sorsaffari** [comment]
@maydanw I'm not sure if I understand the issue clearly.

Workbase, as of version `1.2.3` (I believe), does display an error message stating that _"Only match get and compute path queries are supported"_, when the user tries to run a query that's unsupported, including an `insert` query.

feel free to reopen this issue, if you believe it's still relevant.
