### ISSUE TITLE
Workbase does not clear graphs between queries

### ISSUE THREAD

**Issue by neomatrix369** [graknlabs/workbase#256]
## Description

I was switching between queries and I could see it overlay the results on top of each other. 

## Environment

1. Grakn version: 1.6.2
2. OS of Grakn server: Linux 812faf5f3972 4.19.76-linuxkit (Docker container)
3. Workbase version:  1.2.7
4. OS of Workbase: Mac OS 10.13.6
5. Other environment details:

## Reproducible Steps

Enter a query that will produce a small graph.

Then enter another query that will produce a small graph.

Finally, enter a query that will produce a medium to a large graph.

At each stage, you can see the different overlapping behaviours.

## Expected Output

New graphs for each query, able to clear queries manually.

## Actual Output

Graphs are getting overlayed between the queries, sometimes it does clear the old graph only when the new graph is bigger than the previous one.

![Screen Shot 2020-02-02 at 13 46 51](https://user-images.githubusercontent.com/1570917/73609130-912f7580-45c2-11ea-92b4-ffef4333694b.png)
 
## Additional information

The issue is raised on the back of [slack channel discussions](https://grakn-community.slack.com/archives/C3DS7RW2J/p1580049491044900).

**Comment by sorsaffari** [comment]
@neomatrix369 this is the intended behaviour, as quite often an ongoing investigation requires running multiple queries. you can always choose to clear the graph manually, in between queries.
