### ISSUE TITLE
Workbase is not notarizated by Apple

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/workbase#266]
The following lines are meant to build Workbase and sign it with a valid Apple certificate. 
https://github.com/graknlabs/workbase/blob/fa9056c8f880e98acb2a4409dcc7896cc0bd7c80/.circleci/config.yml#L110-L112

However, when trying to run Workbase (downloaded from the release page) Apple still warns the user that the application is not from a recognised developer.

I have already verified that the certificate won't expire until `Sep 20 14:47:41 2023 GMT` and that the env variables from the snippet above are in fact defined and set on CircleCI.

**Comment by vmax** [comment]
@sorsaffari our app is still *signed* properly, as shown by the following:

```
vmax@ghost workbase master ? codesign -dv --verbose=4  /Volumes/Grakn\ Workbase\ 1.2.7/Grakn\ Workbase.app
Executable=/Volumes/Grakn Workbase 1.2.7/Grakn Workbase.app/Contents/MacOS/Grakn Workbase
Identifier=grakn.workbase
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20200 size=270 flags=0x0(none) hashes=3+3 location=embedded
VersionPlatform=1
VersionMin=657664
VersionSDK=658432
Hash type=sha256 size=32
CandidateCDHash sha1=fae3e3a20fea140519f820b25009b6382c5f32b5
CandidateCDHashFull sha1=fae3e3a20fea140519f820b25009b6382c5f32b5
CandidateCDHash sha256=3ee58f55f74565f4b8356ca0dfdea899696bda73
CandidateCDHashFull sha256=3ee58f55f74565f4b8356ca0dfdea899696bda73b13f5f607dd55e730831bc3a
Hash choices=sha1,sha256
CMSDigest=d88950e4ae94ea1bb26a022fcffacb2ca20ecfd3f771f19e97e297be2dac12aa
CMSDigestType=2
Page size=4096
CDHash=3ee58f55f74565f4b8356ca0dfdea899696bda73
Signature size=8924
Authority=Developer ID Application: Grakn Labs Limited (RHKH8FP9SX)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=12 Dec 2019, 23:06:56
Info.plist entries=23
TeamIdentifier=RHKH8FP9SX
Sealed Resources version=2 rules=13 files=11
Internal requirements count=1 size=176
```

What we're lacking, however, is _notarization_ from Apple. I'll try adding it according to 
 [this](https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/) tutorial
