### ISSUE TITLE
Have two Keyspaces.test.js in the repo

### ISSUE THREAD

**Issue by lriuui0x0** [graknlabs/workbase#268]
## Description

`keyspaces.test.js` contains the latest contents.
`Keyspaces.test.js` is the name we want to use for the file to keep it consistent with all other test files.

So we should remove `Keyspaces.test.js` and rename `keyspaces.test.js` to `Keyspaces.test.js`

**Comment by vmax** [comment]
@lriuui0x0 description is kind of unclear: which one should be kept and which one should we remove?

**Comment by lriuui0x0** [comment]
@vmax I have elaborated a bit more.
