### ISSUE TITLE
Workbase allows to execute only one query . All subsequent queries return ```NullPointerException```

### ISSUE THREAD

**Issue by adiv5** [graknlabs/workbase#274]
Please replace every line in curly brackets ( { like this } ) with appropriate answers, and remove this line.

## Description

I loaded the data onto my keyspace. 

Now on loading the workbase and selecting the keyspace, executing the 1st query returns results as expected, but any subsequent queries return null

In the server logs , I get this error
```
2020-04-29 17:25:46,758 [transaction-listener] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
java.lang.NullPointerException: null
```
here is the [schema](https://docs.google.com/document/d/1ND7iN2hZBFuj5vyz8aQXNr_XZLjjqmTCVPE_UpJllQE/edit?usp=sharing)

## Environment

1. Grakn version: 1.6.2
2. OS of Grakn server: Ubuntu 18.04 LTS
3. Workbase version:1.2.2
4. OS of Workbase: Ubuntu 18.04 LTS
5. Other environment details:

## Reproducible Steps

Steps to create the smallest reproducible scenario:
0. Install Grakn from pip and grakn workbase 1.2.2
1. Start the server.
2. make a keyspace and load the schema in it
3. migrate some data into the keyspace 
4. Now open Workbase, select your keyspace
5. make any query, it should work
6. make another query , `it fails with error Null. please check server logs for stack trace`
7. check Server Logs. Should get something like 
```
2020-04-29 17:25:46,758 [transaction-listener] ERROR g.c.s.r.SessionService$TransactionListener - Runtime Exception in RPC TransactionListener: 
java.lang.NullPointerException: null
```

## Expected Output

results to the queries i put in. Any number of queries can be answered

## Actual Output

only one query is executed, rest all go in NULLPOINTEREXCEPTION

 
## Additional information

I tried checking via console if getting error . but no. Console works fine. Problem is mostly for the workbase

Workbase was working fine few hours back. now it shows this error

**Comment by sorsaffari** [comment]
Workbase `1.2.2` does not support Grakn core `1.6.2`.
here is the dependency table for Workbase: http://dev.grakn.ai/docs/workbase/overview
