### ISSUE TITLE
CI pipeline

### ISSUE THREAD

**Issue by vmax** [graknlabs/workbase#32]
Current goal of CI integration is as follows:
* ensure Workbase is _built_ on all three platforms (Linux and Mac through native CircleCI, for Windows a GCP instance is provisioned and controlled via `ssh`) — `npm run build`
[2] * ensure Workbase is _unit-tested_ on all three platforms — `npm run unit`
[3] * ensure Workbase is _e2e-tested_ on all three platforms — `npm run e2e`

Steps [2] and [3] require running Grakn server with [data](https://github.com/graknlabs/workbase/blob/master/test/helpers/basic-genealogy.gql) loaded into `gene` keyspace which will be obtained through building it with `bazel`

Note: `bazel` is only used for obtaining `//:distribution` and providing `node`/`npm` of certain version defined in `WORKSPACE`

**Comment by lolski** [comment]
FYI, this issue supersedes https://github.com/graknlabs/workbase/issues/17
