### ISSUE TITLE
Error when defining a sub-entity type

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/workbase#365]
## Description

I am defining an entity as a sub type of another entity through the schema editor. When I click submit, however, I get an error. 

## Environment

1. Grakn version: `grakn-core-2.0.0-alpha-9`
2. OS of Grakn server: Mac OS 10
3. Workbase version: `Grakn Workbase 2.0.0-alpha`
4. OS of Workbase: Mac OS 10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run Grakn server 
2. Define any entity in the schema editor. For example `person`
3. Then define a sub type to that entity, for example, `sub-person sub person`
4. After a few seconds, an error will appear: `2 UNKNOWN:`

## Expected Output

Entity created.

## Actual Output

![image](https://user-images.githubusercontent.com/20223184/111076056-a58eb300-84e2-11eb-9704-d004f24c6e9a.png)

**Comment by lriuui0x0** [comment]
Fixed.
