### ISSUE TITLE
Error when sub typing a relation, cannot remove inherited role type

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/workbase#366]
## Description

When I sub type a relation, I am unable to do so because of Workbase's UX. 

![image](https://user-images.githubusercontent.com/20223184/111077147-4c754e00-84e7-11eb-8726-0e2f178a1c51.png)
Workbase automatically populates the "spouse" role and any other roles inherited from its parent. I cannot remove this. Which means I cannot define the new sub relation. 

## Environment

Grakn version: grakn-core-2.0.0-alpha-9
OS of Grakn server: Mac OS 10
Workbase version: Grakn Workbase 2.0.0-alpha
OS of Workbase: Mac OS 10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run Grakn server
2. Define any type of relation, for example: `marriage sub relation, relates spouse;`
3. Then define a sub type for that relation, for example: `sub-marriage sub relation; `
4. When I click submit I get an error

## Expected Output

Defining of sub relation

## Actual Output
![image](https://user-images.githubusercontent.com/20223184/111076643-11721b00-84e5-11eb-8d11-4a4ccd101b43.png)

**Comment by lriuui0x0** [comment]
Fixed.
