### ISSUE TITLE
Default query template adds `get` to query

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/workbase#367]
## Description

The default query template in Workbase adds `get` to each query. This is a UX remnant from 1.x which should be removed for 2.0.
![image](https://user-images.githubusercontent.com/20223184/111077299-053b8d00-84e8-11eb-966a-84b0e52bc3dd.png)

## Environment

Grakn version: grakn-core-2.0.0-alpha-9
OS of Grakn server: Mac OS 10
Workbase version: Grakn Workbase 2.0.0-alpha
OS of Workbase: Mac OS 10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run Grakn server
2. Open Workbase's visualiser
3. Open the query template builder and click on any type
4. This will automatically add `get` to the end of each query

## Actual Output

![image](https://user-images.githubusercontent.com/20223184/111076406-197d8b00-84e4-11eb-939d-e17b4d0eae98.png)

**Comment by lriuui0x0** [comment]
Fixed.
