### ISSUE TITLE
Invalid Transaction Operation when switching from data to schema editor

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/workbase#368]
## Description

When querying for data in the visualiser, if I then go into the schema editor to define a new type, I get an Invalid Transaction Operation. 

## Environment

Grakn version: grakn-core-2.0.0-alpha-9
OS of Grakn server: Mac OS 10
Workbase version: Grakn Workbase 2.0.0-alpha
OS of Workbase: Mac OS 10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run Grakn server
2. Run a query in Workbase visualiser in keyspace #1
3. Switch to the schema editor in keyspace #1 and define any new type, for example an entity
4. Go back to the visualiser, and query for any data in keyspace #2
5. Then go back to schema editor for keyspace #1, try to define a new type
6. See error at the bottom (`Invalid Transaction Operation`)

![image](https://user-images.githubusercontent.com/20223184/111076330-d1f6ff00-84e3-11eb-9289-64dafc5dd039.png)

**Comment by lriuui0x0** [comment]
@tomassabat I cannot reproduce this.

**Comment by tomassabat** [comment]
@lriuui0x0 I have updated the steps.

**Comment by lriuui0x0** [comment]
This is fixed.
