### ISSUE TITLE
Workbase allows to create types that start with numbers

### ISSUE THREAD

**Issue by tomassabat** [graknlabs/workbase#369]
## Description

Grakn doesn't allow types to start with numbers. If we try to do this in the console this fails. However, when we use Workbase instead, Grakn successfully defines types that start with numbers. 

## Environment

Grakn version: grakn-core-2.0.0-alpha-9
OS of Grakn server: Mac OS 10
Workbase version: Grakn Workbase 2.0.0-alpha
OS of Workbase: Mac OS 10

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Run Workbase
2. Go into schema editor
3. Define a type with a name that starts with numbers. For example, an entity type with name: `1115abc`
4. This will succeed, but it should fail

## Expected Output

An error, for example this is what Console gives when attempting to do the same: 
![image](https://user-images.githubusercontent.com/20223184/111077482-db369a80-84e8-11eb-988a-900efcbd0613.png)

## Actual Output

Workbase is able to create types that start with numbers: 
![image](https://user-images.githubusercontent.com/20223184/111076681-3bc3d880-84e5-11eb-80b4-bd193831ca83.png)
![image](https://user-images.githubusercontent.com/20223184/111076612-ee476b80-84e4-11eb-90bb-ecddb8dfe46d.png)
![image](https://user-images.githubusercontent.com/20223184/111077495-e689c600-84e8-11eb-965b-b259213ad89d.png)

**Comment by lriuui0x0** [comment]
lol @alexjpwalker this might be a client-server api bug :)

**Comment by alexjpwalker** [comment]
This issue should be tackled on the server side. I've raised https://github.com/graknlabs/grakn/issues/6253 which will close this issue when resolved.
