### ISSUE TITLE
match $x sub thing; get; throws error

### ISSUE THREAD

**Issue by sorsaffari** [graknlabs/workbase#38]
Grakn version: 1.4.0

## Reproducing steps:
1. select any keyspace
2. in Graql Editor, enter `match $x sub thing; get;`
3. execute

## Expected outcome:
visualise all labels with no errors.

## Actual outcome
visualises all (?) labels including one blank node and the error message: n.attributes is not a function

**Comment by marco-scoppetta** [comment]
@sorsaffari @Irtazaraza please let's prioritise this bug

**Comment by sorsaffari** [comment]
@marco-scoppetta could you please elaborate why you'd give this high priority?

**Comment by marco-scoppetta** [comment]
this is a basic query that people tend to try as a first thing when opening Workbase. Also it should be a fairly easy fix
