### ISSUE TITLE
Schema transaction in Workbase schema editor does not close 

### ISSUE THREAD

**Issue by daniel-crowe** [graknlabs/workbase#382]
## Description

After opening the schema editor in Grakn Workbase, and then closing it; attempting to open a transaction in Console returns an error. 

## Environment

Grakn version: grakn-core-2.0.0-alpha-9
OS of Grakn server: Mac OS 10
Workbase version: Grakn Workbase 2.0.0-alpha-2.4733
OS of Workbase: Mac OS 10

## Reproducible Steps

1. Run Grakn and start Workbase
2. Open schema editor and select database
3. Close schema editor 
4. in Grakn Console, open schema transaction database
5. Error is returned and cannot open transaction 

## Expected Output
- schema transaction closes after closing Workbase schema editor 

## Actual Output

Error is returned: 
`[SSN03] Invalid Session Operation: Could not acquire lock for schema session. Another schema session may have been left open. Please check server logs for the stack trace`

**Comment by tomassabat** [comment]
@lriuui0x0 
This doesn't seem solved, see below, I went from the schema designer back to the visualiser, but could not open a schema transaction. 

![image](https://user-images.githubusercontent.com/20223184/111375178-dd8a2780-8695-11eb-9e08-a9c6f3fd1c80.png)

**Comment by lriuui0x0** [comment]
@tomassabat This issue I think should be fixed.
