### ISSUE TITLE
Inferred relationships/entities currently cannot be expanded/explained because the explanation pattern is not complete

### ISSUE THREAD

**Issue by Irtazaraza** [graknlabs/workbase#43]
Reference to Inferred concepts is lost between multiple transactions.
e.g. 
If A is an inferred relationship and has roleplayers B and C. 
When we retrieve A in transaction 1, we need a way to retrieve role players B and C in transaction 2

**Comment by sorsaffari** [comment]
we resolved this issue by using a single long-living transaction. Workbase should go back to using multiple transactions when the necessary changes are made in the reasoner.
