### ISSUE TITLE
Flaky jest test on Windows

### ISSUE THREAD

**Issue by Irtazaraza** [graknlabs/workbase#81]
## Description
Flaky jest test

## Environment

1. OS (where Grakn server runs):Windows 10
2. Grakn version (and platform): Grakn 1.5

## Reproducible Steps

https://circleci.com/gh/graknlabs/workbase/629

error message:
```
    jest: failed to cache transform results in: C:/Users/circleci/AppData/Local/Temp/jest/jest-transform-cache-2af1f1cd6f842a951c23edf0f89257db-9a9740a15a86d43e50d470de08968b86/37/SharedUtils_37fceef953d3f7697677ef15066d0e38.map
    Failure message: EBADF: bad file descriptor, close
```

## Expected Output
test pass

## Actual Output
test fails
 
## Additional information
https://github.com/facebook/jest/issues/3630
https://github.com/facebook/jest/issues/7709

**Comment by dgreene1** [comment]
Any updates on this?

**Comment by Irtazaraza** [comment]
Will be looking into this, this week. I believe the issue is related to the Jest version and some other dependencies. Will keep you updated :)

**Comment by dgreene1** [comment]
Thank you so much! Btw, I’m finding slightly better results when I delete the cache but leave the jest folder in the cache there.

**Comment by Irtazaraza** [comment]
Thanks for the insight. I'll try that too. :)
