### ISSUE TITLE
Mac Client not working v1.1.1

### ISSUE THREAD

**Issue by rtatay** [graknlabs/workbase#83]
Mac OSX version 1.1.1 cannot be opened, downloaded from releases page but for some reason it can't be opened.

**Comment by Irtazaraza** [comment]
Hi @rtatay 

Could you please provide a little more context to which Grakn version you are running, and what kind of error you are getting on Workbase? Or is the Workbase app just not launching?

Thanks,
Syed

**Comment by rtatay** [comment]
Apologies, was in a hurry yesterday. Workbase version is 1.1.1 . The error message popup is below:

<img width="418" alt="Screen Shot 2019-03-13 at 9 42 10 AM" src="https://user-images.githubusercontent.com/8494810/54292890-9764cf80-4574-11e9-94db-8d59e48c02bb.png">

I noticed the Grakn Workbase.app/Contents/MacOS/Grakn Workbase binary is not set to executable permissions:

$ ls -ltr
total 40
-rw-rw-r--  1 rcota  US\Domain Users  18336 Feb  8 09:47 Grakn Workbase

after issuing a chmod +x I get the following error when attempting to start from command line:

$ chmod +x Grakn\ Workbase 

$ ./Grakn\ Workbase 
dyld: Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Users/rcota/Downloads/Grakn Workbase.app/Contents/MacOS/./Grakn Workbase
  Reason: no suitable image found.  Did find:
	/Users/.../Grakn Workbase.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/Users/.../Grakn Workbase.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1
Abort trap: 6

**Comment by Irtazaraza** [comment]
Hi @rtatay 

Thanks for your response. 
Could i also know your Mac OS version so i can try to reproduce it at our end?

**Comment by rtatay** [comment]
It's Mojave, 10.14.3

**Comment by rtatay** [comment]
Any luck with the issue?

**Comment by Irtazaraza** [comment]
Hi @rtatay ,

So i was not able to reproduce the issue on my end and i have the same Mac OS version. Did you download workbase 1.1.1 from the release page? 

Can you try building workbase on your machine?

Steps:
`Clone repo`
`cd workbase`
`npm install`
`npm run build`

**Comment by rtatay** [comment]
Ok, so this worked!

Not sure why I was getting an error from the one downloaded.
